Repository btcven/turpial-firmware, pull requests merged in 2020-04, with the labels that each got.

#130 traivs: update esp-idf commit.
  .travis.yml
Labels: Type: bug

#131 components: fix warnings and errors
  components/HMI/src/HumanInterface.cpp
  components/HMI/src/HumanInterface.h
  components/HMI/src/UserButton.cpp
  components/HMI/src/UserButtonHandler.cpp
  components/HTTP/src/Websocket.cpp
  components/Network/src/WiFi.cpp
  components/Util/src/Base64.cpp
  components/Util/src/Serialization.cpp
Labels: Type: bug, Type: enhancement

#129 sending and receiving data from esp32 to cc1312 radio module
  components/HTTP/CMakeLists.txt
  components/HTTP/src/RESTServer.cpp
  components/HTTP/src/RESTServer.h
  components/HTTP/src/Websocket.cpp
  components/HTTP/src/Websocket.h
  components/Radio/src/Radio.cpp
  components/Radio/src/Radio.h
  main/defaults.h
  main/main.cpp
Labels: Type: feature

#133 2020 04 16 test http
  components/HTTP/src/HttpServer.cpp
  components/HTTP/src/HttpServer.h
  components/HTTP/src/RESTServer.cpp
  components/HTTP/test/CMakeLists.txt
  components/HTTP/test/testHttpServer.cpp
  test/sdkconfig.defaults
Labels: Type: enhancement

#132 components/HTTP: chat uart communication
  components/HTTP/src/RESTServer.cpp
  components/HTTP/src/Websocket.cpp
  components/HTTP/src/Websocket.h
  components/Radio/src/Radio.cpp
  components/Radio/src/Radio.h
  main/main.cpp
Labels: Status: Ready for review, Type: feature

#134 2020 04 20 decode message
  components/HTTP/src/Websocket.cpp
  components/HTTP/src/Websocket.h
  main/main.cpp
Labels: Status: Ready for review

#135 chat: uart RX
  components/HTTP/src/Websocket.cpp
  components/HTTP/src/Websocket.h
  components/Radio/CMakeLists.txt
  components/Radio/src/Radio.cpp
  components/Radio/src/Radio.h
  components/Util/src/Hex.cpp
  main/main.cpp
Labels: Status: Ready for review, Type: enhancement
