Repository btcven/turpial-firmware, pull requests merged in 2020-05, with the labels that each got.

#141 2020 04 27 https autentication
  components/HTTP/src/RESTServer.cpp
  components/HTTP/src/Websocket.cpp
  components/NVS/src/Credentials.cpp
  components/NVS/src/Credentials.h
  components/NVS/src/Storage.cpp
  components/NVS/src/Storage.h
  main/main.cpp
Labels: Status: Ready for review

#142 add basic Kconfig file
  components/HTTP/src/RESTServer.cpp
  main/Kconfig.projbuild
  main/defaults.h
  main/main.cpp
Labels: Status: Ready for review, Type: enhancement

#148 Verify that we comply with the coding style
  components/ESC/src/FuelGauge.cpp
  components/HMI/src/HumanInterface.cpp
  components/HMI/src/HumanInterface.h
  components/HMI/src/UserButton.cpp
  components/HTTP/src/HttpServer.cpp
  components/HTTP/src/RESTServer.cpp
  components/HTTP/src/Websocket.cpp
  components/NVS/src/Credentials.cpp
  components/Network/src/WiFi.cpp
  components/Radio/src/Radio.cpp
Labels: Status: Ready for review, Type: enhancement

#146 sdkconfig: disable C++ exceptions
  sdkconfig.defaults
  test/sdkconfig.defaults
Labels: Type: enhancement

#145 sdkconfig: enable lwIP IPv6 SLAAC
  sdkconfig.defaults
Labels: Type: feature

#153 components/Network: add SLIP network interface
  .travis.yml
  README.md
  components/Network/src/Slip.cpp
  components/Network/src/Slip.h
  main/Kconfig.projbuild
  main/main.cpp
  sdkconfig.defaults
Labels: Status: Ready for review, Type: feature

#157 Update license heading for all source files this closes #154
  components/ESC/src/BQ27441_Constants.h
  components/ESC/src/Battery.cpp
  components/ESC/src/Battery.h
  components/ESC/src/FuelGauge.cpp
  components/ESC/src/FuelGauge.h
  components/HMI/src/HumanInterface.cpp
  components/HMI/src/HumanInterface.h
  components/HMI/src/UserButton.cpp
  components/HMI/src/UserButton.h
  components/HMI/src/UserButtonHandler.cpp
  components/HMI/src/UserButtonHandler.h
  components/HTTP/src/CheckConnections.cpp
  components/HTTP/src/CheckConnections.h
  components/HTTP/src/HttpServer.cpp
  components/HTTP/src/HttpServer.h
  components/HTTP/src/Message.cpp
  components/HTTP/src/Message.h
  components/HTTP/src/RESTServer.cpp
  components/HTTP/src/RESTServer.h
  components/HTTP/src/Websocket.cpp
  components/HTTP/src/Websocket.h
  components/NVS/src/Credentials.cpp
  components/NVS/src/Credentials.h
  components/NVS/src/Storage.cpp
  components/NVS/src/Storage.h
  components/Network/src/Slip.cpp
  components/Network/src/Slip.h
  components/Network/src/WiFi.cpp
  components/Network/src/WiFi.h
  components/Network/src/WiFiEventHandler.cpp
  components/Network/src/WiFiEventHandler.h
  components/Radio/src/Radio.cpp
  components/Radio/src/Radio.h
  components/Task/src/Task.cpp
  components/Task/src/Task.h
  components/Util/src/Base64.cpp
  components/Util/src/Base64.h
  components/Util/src/ErrUtil.h
  components/Util/src/Hex.cpp
  components/Util/src/Hex.h
  components/Util/src/Sema.cpp
  components/Util/src/Sema.h
  components/Util/src/StringUtil.cpp
  components/Util/src/StringUtil.h
  components/VAINA/src/Vaina.cpp
  main/defaults.h
  main/main.cpp
Labels: Status: Ready for review, Type: enhancement

#155 components/Network: refactor network interfaces.
  components/HTTP/src/RESTServer.cpp
  components/Network/CMakeLists.txt
  components/Network/Kconfig
  components/Network/include/Network/Network.h
  components/Network/include/Network/Slip.h
  components/Network/include/Network/WiFi.h
  components/Network/include/Network/WiFiEventHandler.h
  components/Network/src/Network.cpp
  components/Network/src/Slip.cpp
  components/Network/src/WiFi.cpp
  components/Network/src/WiFiEventHandler.cpp
  components/Network/test/TestWiFi.cpp
  components/VAINA/src/Vaina.h
  main/Kconfig.projbuild
  main/main.cpp
Labels: Status: Ready for review, Type: enhancement

#162 update codespell
  .travis.yml
  dist/tools/codespell/check.sh
Labels: Status: Ready for review

#161 turpial-firmware: enable RTR_ADV for esp_wifi_ap
  Kconfig
  Makefile
  main.c
Labels: Status: Ready for review, Type: feature

#164 turpial-firmware: add slipdev interface.
  Makefile
  main.c
Labels: Status: Ready for review, Type: enhancement

#165 turpial-firmware: add vaina module
  Makefile
  main.c
  sys/Makefile
  sys/Makefile.dep
  sys/Makefile.include
  sys/include/net/vaina.h
  sys/net/Makefile
  sys/net/vaina/Kconfig
  sys/net/vaina/Makefile
  sys/net/vaina/vaina.c
Labels: Status: Ready for review

#167 202 05 28 add wifi settings
  Makefile
  sys/Makefile.dep
  sys/include/storage/nvs.h
  sys/include/storage/wifisettings.h
  sys/storage/Makefile
  sys/storage/nvs/nvs.c
  sys/storage/wifisettings/Makefile
  sys/storage/wifisettings/wifisettings.c
Labels: Status: Ready for review
