Repository btcven/turpial-firmware, pull requests merged in 2020-03, with the labels that each got.

#103 HTTP server implementation
  components/HTTP/CMakeLists.txt
  components/HTTP/src/HttpParser.cpp
  components/HTTP/src/HttpParser.h
  components/HTTP/src/HttpRequest.cpp
  components/HTTP/src/HttpRequest.h
  components/HTTP/src/HttpResponse.cpp
  components/HTTP/src/HttpResponse.h
  components/HTTP/src/HttpServer.cpp
  components/HTTP/src/HttpServer.h
  components/HTTP/src/HttpServerHandler.cpp
  components/HTTP/src/HttpServerHandler.h
  components/HTTP/src/Socket.cpp
  components/HTTP/src/Socket.h
  components/HTTP/src/WebSocket.cpp
  components/HTTP/src/WebSocket.h
  components/HTTP/src/WsHandlerEvents.h
  components/NVS/src/Storage.cpp
  components/NVS/src/Storage.h
  main/CMakeLists.txt
  main/defaults.h
  main/main.cpp
  sdkconfig
Labels: invalid

#104 sdkconfig: add sdkconfig.defaults file
  .gitignore
  sdkconfig
  sdkconfig.defaults
  test/sdkconfig
  test/sdkconfig.defaults
Labels: Type: enhancement

#106 components: remove BLE, BLEPreferences
  components/BLE/CMakeLists.txt
  components/BLE/src/Advertising.cpp
  components/BLE/src/Advertising.h
  components/BLE/src/Characteristic.cpp
  components/BLE/src/Characteristic.h
  components/BLE/src/Server.cpp
  components/BLE/src/Server.h
  components/BLE/src/Service.cpp
  components/BLE/src/Service.h
  components/BLE/src/Uuid.cpp
  components/BLE/src/Uuid.h
  components/BLE/test/CMakeLists.txt
  components/BLE/test/TestBLEAdvertising.cpp
  components/BLE/test/TestBLEServer.cpp
  components/BLE/test/TestBLEUuid.cpp
  components/BLEPreferences/CMakeLists.txt
  components/BLEPreferences/src/BLEPreferences.cpp
  components/BLEPreferences/src/BLEPreferences.h
  main/CMakeLists.txt
  main/defaults.h
  main/main.cpp
Labels: Type: enhancement

#107 Fix codespell warning
  main/main.cpp
Labels: Type: enhancement

#108 components: fix HTTP, Network warnings
  components/HTTP/src/HttpServerHandler.cpp
  components/Network/src/WiFi.cpp
  components/Network/src/WiFi.h
  components/Network/src/WiFiEventHandler.cpp
  components/Network/src/WiFiEventHandler.h
Labels: Type: enhancement

#109 Feature/hmi 03 04 2020
  components/HMI/CMakeLists.txt
  components/HMI/src/HumanInterface.cpp
  components/HMI/src/HumanInterface.h
  components/HMI/src/UserButton.cpp
  components/HMI/src/UserButton.h
  components/HMI/src/UserButtonHandler.cpp
  components/HMI/src/UserButtonHandler.h
  main/CMakeLists.txt
  main/defaults.h
  main/main.cpp
Labels: Type: feature

#112 README.md: fix broken link
  README.md
Labels: Type: enhancement

#121 Workaround esp_https_server compilaton bug
  .travis.yml
  components/HTTP/src/HttpServer.cpp
  components/HTTP/src/HttpServer.h
  components/HTTP/src/RESTServer.cpp
  main/defaults.h
Labels: Type: enhancement
